### ISSUE TITLE
Mods folder not syncing

### ISSUE THREAD

**Issue by instinxx** [Sajeyson-Dev/CF-MultiMC-Sync#2]
Configure config.json
Run Sync.bat
Modpack appears in MMC
Restart MMC
Mods dont sync

**Comment by sajeyson012** [comment]
Do you see console errors?
Show your config and what is your OS?

Sorry for late response.

**Comment by instinxx** [comment]
![image](https://user-images.githubusercontent.com/1753699/172390405-e96d8f23-6b80-4db2-91fd-c51215416bfe.png)
![image](https://user-images.githubusercontent.com/1753699/172390612-88776bac-dd5f-4dca-b2cb-8f499d7fe6a6.png)

No errors in the window when I run sync

**Comment by sajeyson012** [comment]
Ok. Check if MultiMC not created `minecraft` instead using `.minecraft` inside synced instance.

**Comment by sajeyson012** [comment]
Oh... That's very weird. All that stuff (except `instance.cfg and `mmc-pack.json`) should be inside `.minecraft`, but... That won't happens for me though.

![CF-MultiMC-Sync-1 0 1 6_7_2022 5_00_16 PM](https://user-images.githubusercontent.com/106702970/172399617-7ea14dba-b8d2-409b-bfca-a4752b8095e8.png)

![CF-MultiMC-Sync-1 0 1 6_7_2022 5_00_21 PM](https://user-images.githubusercontent.com/106702970/172399659-bd0e0f14-d775-40c0-9f28-4e8322eff42e.png)

**Comment by sajeyson012** [comment]
Also, are you on Windows 11?

**Comment by instinxx** [comment]
Yes its W11

**Comment by sajeyson012** [comment]
So weird. Like I literally passing through `.minecraft` and creating symlink there ([see code](https://github.com/Sajeyson-Dev/CF-MultiMC-Sync/blob/master/app.js#L136)).
I will continue research and comment it here, if I find something.
Also, do you have checked 'show hidden files' option in explorer? Because that screenshot with a console output shows that it recognizes files and folder from instance.

**Comment by instinxx** [comment]
![image](https://user-images.githubusercontent.com/1753699/172409823-bcbdbd38-218f-4b1e-b52f-f079aaf4f795.png)
 
Its very odd

**Comment by sajeyson012** [comment]
Here is new [app.js](https://github.com/Sajeyson-Dev/CF-MultiMC-Sync/files/8854384/app.-.test.zip). I added callback, so if folder already exists or something is wrong it gives a console error. Try replacing it and run again. For tests change `"multiMcInctanceFolder"` to some another clear folder.

**Comment by sajeyson012** [comment]
Yea... It works if Authenticated Users have Full Control.

**Comment by sajeyson012** [comment]
Or at least 'Read' is checked.
![Instances Properties 6_7_2022 8_34_16 PM](https://user-images.githubusercontent.com/106702970/172446698-127fe884-04dc-4727-9933-6c6847b74aca.png)

**Comment by instinxx** [comment]
When I tried to give the root folder (for me "Minecraft Stuff") I got this, bit of interesting fuckery 
![image](https://user-images.githubusercontent.com/1753699/172446897-27ae5556-fe1a-4c94-ae29-d69d66b557e2.png)

Just FYI

**Comment by instinxx** [comment]
![image](https://user-images.githubusercontent.com/1753699/172448084-76c70a45-bb83-4df1-b204-a7cf70b296ac.png)

**Comment by instinxx** [comment]
![image](https://user-images.githubusercontent.com/1753699/172448266-c166f8dc-6aef-44cb-a3bc-799d57f35469.png)

**Comment by sajeyson012** [comment]
Oh, about the error, do you cleared those two fail synced instances from multimc instances folder?

**Comment by instinxx** [comment]
No. Will try now

**Comment by instinxx** [comment]
Same error I am afraid.

**Comment by sajeyson012** [comment]
Still no permission with errno: -4048?

**Comment by instinxx** [comment]
![image](https://user-images.githubusercontent.com/1753699/172449692-9f379305-87fc-4ceb-87f2-6404b930107e.png)

**Comment by sajeyson012** [comment]
Oh yea... try adding it to syncBlacklist in config. Same as I did with .curseclient

**Comment by instinxx** [comment]
oh nvm ....spelling

**Comment by instinxx** [comment]
so now it stops at 
![image](https://user-images.githubusercontent.com/1753699/172450895-9d6f271d-dda7-493f-8c8d-f6e16e9783b0.png)

**Comment by sajeyson012** [comment]
Do full control applied to sub folders/files?

**Comment by instinxx** [comment]
on  CF side or MMC side?

**Comment by instinxx** [comment]
NVM it is set to inherit from parent folder

**Comment by sajeyson012** [comment]
Probably on CF, because in MMC it creates new folder with required permissions, then puts links in created empty folder.

**Comment by instinxx** [comment]
OK Fixed it

I had to do this:
To enable a given user to create symlinks (by giving the user SeSymbolicLinkPrivilege), do the following:

Run the Local Security Policy Editor (secpol.msc). It will require Administrator access.
Look under "Local Policies" -> "User Rights Assignment". Find the "Create symbolic links" entry.
Double-click the entry to open it, then press [Add User or Group...].
In the box that appears, type your Windows username and press [Check Names]. It should change to a fully-qualified name, with an underline. If it doesn't, you should try other forms of the username. You can also click [Advanced] to search a list of options.
Once the user name is underlined in the box, hit [OK] on the "Select Users and Groups" window, then hit [OK] on the "Create symbolic link Properties" window.
If the user in question is logged in, log out and log in again. That user should now be able to create symbolic links without needing admin privileges.

**Comment by sajeyson012** [comment]
Yes! I literally just rn found this on stackoverflow https://i.stack.imgur.com/XD62F.png

**Comment by sajeyson012** [comment]
Now you can use that original app.js file, cuz this will give an error if you try using it again in not empty instance.

**Comment by instinxx** [comment]
but! 

When I launch the pack, instead of 300+ Mods loading I get 2. Usually in MMC I need to go to edit the instance, select loader mods and add the mod(s) not sure if it can be done programmatically?

**Comment by instinxx** [comment]
Success! Thanks for the help.
